### ISSUE TITLE
Lutris installer requires force quit in order to continue

### ISSUE THREAD

**Issue by nmlynch94** [TormStorm/jagex-launcher-linux#11]
# Problem
The installer freezes after clicking "Install". It still works in the background, but requires the user to use something like `xkill` or pipe ps aux into kill somehow which is not great user experience. 

# Reproduce
1. Run the Jagex Launcher installer from lutris https://lutris.net/games/jagex-launcher/
2. Advance through the prompts until it asks you to click "Installer"
3. At this point, the launcher appears unresponsive, although it can still be moved and minimized. Maximize and close don't work.
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/1f8c42e0-e342-4f98-8a9e-653ab6c895f2)

## Potential Solutions
1. Get the 'x' button on the window manager to work so the user doesn't need to use the CLI (similar to league of legends installer)
2. Resolve the launcher freezing by discovering what missing dependency is causing the window to freeze

In case it is useful, this is also what the windows installer looks like if you press no on the User Account Control popup after clicking "Install". Wine is supposed to disable user account control and run as admin, but may be useful information.
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/47acfacf-6a8b-431a-bd72-b0edb3d2823d)

**Comment by nmlynch94** [comment]
Could not get the window manger to close or the progress bar to work, so I run the launcher in the background and then run a script that checks the install directory every 10 seconds until it is over 200mb for two loops, then I kill the PID of the launcher installer.

**Comment by TormStorm** [comment]
Fixed with #29

**Comment by TormStorm** [comment]
Might be fixed by a Jagex Launcher update in the future by updating the underlying tech of the installer removing the dependence on Internet Explorer to render it.

**Comment by nmlynch94** [comment]
I don't think the dependency on IE11 is what causes this. The Jagex Launcher Installer uses a product from Solid State Networks, and something about this installer technology makes it freeze. 

I tested the installer for swtor, which also uses the same product, but uses CEF instead of IE11 and the installer still freezes after pressing the install button.

**Comment by TormStorm** [comment]
Addressed with #106
